version: "3.3"

services:
    
    standard:
        image: bayrell/cloud_os_standard:0.5.0-20231106_182124
        hostname: "cloud_os_standard.local"
        volumes:
            - "standard_dev:/data"
            - "/home/ubuntu/bayrell/cloud_os_standard_0.5/src:/srv"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/etc/hostname:/etc/hostname_orig:ro"
        ports:
            - "8020:22"
            - "8080:80"
        env_file:
            - ./env.conf
        environment:
            TZ: "Asia/Almaty"
            WWW_UID: 1000
            WWW_GID: 1000
        restart: unless-stopped
        networks:
            - cloud_network
        logging:
            driver: journald
    
volumes:
    standard_dev:
    
networks:
    cloud_network:
        external: true
