version: "3.3"

services:
    
    router_http_node1:
        image: bayrell/cloud_router_http:0.4.0
        volumes:
            - "router_http_data:/data"
            - "/home/ubuntu/bayrell/cloud_router_http/files/root/router.php:/root/router.php"
        ports:
            - "80:80"
        env_file:
            - ./env.conf
        restart: always
        networks:
            - cloud_network
        logging:
            driver: journald
    
volumes:
    router_http_data:
    
networks:
    cloud_network:
        external: true
