version: "3.3"

services:
    
    standard_node1:
        image: bayrell/cloud_os_standard:0.4.1-20220906_191529
        hostname: "cloud_os_standard.local"
        volumes:
            - "standard_node1_data:/data"
            - "/home/ubuntu/bayrell/cloud_os_standard_0.4/src:/srv"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - "8022:22"
            - "8080:80"
        env_file:
            - ./env.conf
        environment:
            TZ: "Asia/Almaty"
            WWW_UID: 1000
            WWW_GID: 1000
        restart: unless-stopped
        networks:
            - cloud_network
        logging:
            driver: journald
    
volumes:
    standard_node1_data:
    
networks:
    cloud_network:
        external: true
