version: "3.3"

services:
    
    standard_node1:
        image: bayrell/cloud_os_standard:0.4.0-20211122_075351
        hostname: "cloud_os_standard.local"
        volumes:
            - "standard_node1_data:/data"
            - "/home/ubuntu/bayrell/cloud_os_standard_0.4:/srv"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - "8022:22"
            - "8080:80"
        env_file:
            - ./env.conf
        environment:
            TZ: "Asia/Almaty"
            APP_URL: "http://cloud.docker0:8080/"
            MYSQL_DATABASE: "cloud_os_standard"
            DOCUMENT_ROOT: "/srv/frontend/html"
            WWW_UID: 1000
            WWW_GID: 1000
            SSH_USER: "mikuro4ka"
            SSH_PASSWORD: "Yf6ugfdCs2LWQUQ6"
        restart: always
        networks:
            - cloud_network
        logging:
            driver: journald
    
    
    code_server:
        image: bayrell/ubuntu_code_server:3.11.0-4-amd64
        hostname: "cloud_os_standard.local"
        volumes:
            - "code_server_data:/data"
            - "/home/ubuntu/bayrell/cloud_os_standard_0.4:/srv"
        ports:
            - "8000:8000"
        environment:
            TZ: "Asia/Almaty"
            APP_URL: "http://cloud.docker0:8080/"
            DOCUMENT_ROOT: "/srv/frontend/html"
            NGINX_CONF: "/srv/nginx_vscode.conf"
            WWW_UID: 1000
            WWW_GID: 1000
        restart: always
        networks:
            - cloud_network
        logging:
            driver: journald
    
    
    router_http_node1:
        image: bayrell/cloud_router_http:0.4.0-20211023_155437
        volumes:
            - "router_http_data:/data"
            - "/home/ubuntu/bayrell/cloud_router_http/files/root/router.php:/root/router.php"
        ports:
            - "80:80"
        env_file:
            - ./env.conf
        restart: always
        networks:
            - cloud_network
        logging:
            driver: journald
    
volumes:
    standard_node1_data:
    code_server_data:
    router_http_data:
    
networks:
    cloud_network:
        external: true
