version: "3.7"

services:
    
    standard:
        image: bayrell/cloud_os_standard:0.3.1-20210211_180534
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "standard_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "../src:/var/www"
        env_file:
            - ./env.conf
        environment:
            MYSQL_DB: "cloud_os_standard"
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - cloud_backend
        ports:
          - target: 80
            published: 8080
            protocol: tcp
            mode: host
          - target: 22
            published: 8022
            protocol: tcp
            mode: host
        logging:
            driver: journald

volumes:
    standard_data:

networks:
    cloud_backend:
        external: true
